name: 01a Hola Mundo

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Hola mundo
      run: echo "Hola mundo desde un push"