name: 04a - Shells

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bash
      shell: bash
      run: echo $0
    - name: Sh
      shell: sh
      run: echo $0
    - name: Por defecto
      run: echo $0