name: 05b - Ejercicio lint JSON

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check node version
      run: node -v
    - name: install jsonlint
      run: |
        sudo apt-get update
        sudo apt-get install -y jsonlint
    - name: lint json
      run: |
        jsonlint-php package.json
   